#1端口
server:
  port: 8005
  
#3连接数据库 jpa
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpa001?serverTimezone=GMT%2B8
    username: root
    password: root 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update   
      show-sql: true
  application:
     name: springCloud-TestProvider
#4 连接注册中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka
